# Generated by Django 4.0.1 on 2022-01-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
