# Generated by Django 4.0.1 on 2022-01-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stockApp', '0004_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopCode', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('EAN_13', models.CharField(max_length=20)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
