# Generated by Django 4.0.1 on 2022-01-13 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0006_basket_shopper_item_basket_shopper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stockApp.product'),
        ),
    ]
