# Generated by Django 4.0.1 on 2022-01-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0007_alter_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='shopCode',
            new_name='shop_code',
        ),
        migrations.AddField(
            model_name='product',
            name='price_in_cents',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.FloatField(default=0),
        ),
    ]
