# Generated by Django 4.0.1 on 2022-01-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0008_rename_shopcode_product_shop_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock',
        ),
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
