# Generated by Django 4.0.1 on 2022-01-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0009_rename_quantity_product_stock_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.shopper')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stockApp.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.order')),
            ],
        ),
    ]
