# Generated by Django 4.0.1 on 2022-01-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0011_remove_purchase_item_remove_purchase_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
